#!/bin/bash
# This file adds the default "push" phase of
# docker autobuild.
#
# Advanced options for Autobuild and Autotest
# see https://docs.docker.com/docker-hub/builds/advanced/
#
# load environment variables from env file
. "$(dirname $0)/env"

# push image with latest tag
docker push ${IMAGE_NAME_LATEST}

# push image with version suffix if necessary
if [[ "$DOCKER_TAG" != "latest" ]]; then
	docker push ${IMAGE_NAME}
fi